on:
    push:
        branches:
            - release/*/*
jobs:
    release:
        uses: ./.github/workflows/npm-release-reusable.yml
        with:
            slack_channel: "#npm-packages"
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
