on:
    push:
        branches:
            - release/*/*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # Fetch full history to get all tags so we can get PREV_VERSION
                  fetch-depth: 0

            - name: Set version enviroment variables
              run: |
                  release_mode=stable
                  next_version=${GITHUB_REF##*/}
                  next_tag="$pkg/v${next_version}"
                  echo "$GITHUB_REF"

                  pkg=$(echo "$GITHUB_REF" | cut -d / -f 4)
                  npm_name=$pkg

                  current_version=0.0.0

                  if [ -f "packages/$pkg/package.json" ]; then
                    current_version="$(jq -r .version "packages/$pkg/package.json")"
                    npm_name="$(jq -r .name "packages/$pkg/package.json")"
                  fi


                  next_tag="$pkg/v${next_version}"

                  if [ "$next_version" = "prerelease" ]; then
                    next_version="${current_version}-dev.${GITHUB_SHA:0:10}"
                    # No tag for prereleases
                    next_tag=
                    release_mode=prerelease
                  fi

                  prev_tag="$(git describe --abbrev=0 --match "$pkg/v*" || true)"
                  prev_version=$(echo "$prev_tag" | sed -E "s/.+v([0-9\.]+)\$/\1/")

                  link_ver="$(echo $next_version | tr -cd '[:alnum:]')"
                  changelog_link="https://github.com/valu-digital/npm-packages/blob/master/packages/$pkg/CHANGELOG.md#v${link_ver}"

                  set -x
                  echo "pkg=$pkg" >> $GITHUB_ENV
                  echo "npm_name=$pkg" >> $GITHUB_ENV
                  echo "next_version=$next_version" >> $GITHUB_ENV
                  echo "next_tag=$next_tag" >> $GITHUB_ENV
                  echo "prev_tag=$prev_tag" >> $GITHUB_ENV
                  echo "prev_version=$prev_version" >> $GITHUB_ENV
                  echo "release_mode=$release_mode" >> $GITHUB_ENV
                  echo "changelog_link=$changelog_link" >> $GITHUB_ENV

            - name: Commit version numbers
              run: |
                  . .github/npm-release.sh
                  jq ".version = \"$next_version\"" package.json > tmp.json
                  mv tmp.json package.json
                  git config user.email "action@github.com"
                  git config user.name "${{ github.actor }}"
                  git add package.json
                  git commit -m "$pkg: v${next_version}"
                  git tag -a "$next_tag" -m "$pkg v$next_version"

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: "Build ${{ env.package }}"
              run: |
                  . .github/npm-release.sh

                  if [ -f package-lock.json ]; then
                      npm ci
                  else
                      npm install
                  fi

                  npm run build

                  npm run test

            - name: Make STABLE release
              if: ${{ env.release_mode == 'stable' }}
              run: |
                  . .github/npm-release.sh
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > "$HOME/.npmrc"
                  npm whoami
                  npm publish
                  rm "$HOME/.npmrc"

                  git push origin HEAD:master
                  git push origin --tags

            - name: Make PRERELEASE release
              if: ${{ env.release_mode == 'prerelease' }}
              run: |
                  . .github/npm-release.sh
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > "$HOME/.npmrc"
                  npm whoami
                  npm publish --tag dev
                  rm "$HOME/.npmrc"

            # - name: Notify prerelease
            #   if: ${{ github.ref == 'refs/heads/release/react-valu-search/prerelease' }}
            #   run: |
            #       . .github/npm-release.sh
            #       slack_message "New \`@valu/react-valu-search\` prelease. \n\nInstall with \`npm install --save-exact @valu/react-valu-search@${next_version}\`"

            # - name: Notify stable release
            #   if: ${{ github.ref != 'refs/heads/release/react-valu-search/prerelease' }}
            #   run: |
            #       . .github/npm-release.sh
            #       slack_message "New \`@valu/react-valu-search\` stable release. \n\nInstall with \`npm install @valu/react-valu-search@^${next_version}\`"

            # - name: Notify about failure
            #   if: failure()
            #   run: |
            #       set -eu
            #       . .github/utils.sh
            #       slack_message '<!channel> '"Failed to make npm release"
